/** ST1 Pro schema generated from docs/product/Debugfile_ST1_Pro.json (Pro_Key: a3cbezgki7lkl8rr) */
export const defaultSchema = [
  {
    attr: 1664,
    canTrigger: true,
    code: 'switch',
    defaultRecommend: false,
    editPermission: true,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_power2',
    id: 1,
    mode: 'rw',
    name: '开关',
    property: {
      type: 'bool',
    },
    type: 'obj',
    subType: 'bool',
  },
  {
    attr: 1152,
    canTrigger: true,
    code: 'mode',
    defaultRecommend: false,
    editPermission: true,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_mode',
    id: 2,
    mode: 'rw',
    name: '工作模式',
    property: {
      range: ['no_mode', 'eco', 'kitchen', 'bath', 'auto_temp'],
      type: 'enum',
    },
    type: 'obj',
    subType: 'enum',
    defaultValue: 'no_mode',
  },
  {
    attr: 1664,
    canTrigger: true,
    code: 'temp_set',
    defaultRecommend: false,
    editPermission: true,
    executable: true,
    extContent: '',
    iconname: 'icon-set',
    id: 7,
    mode: 'rw',
    name: '设置温度',
    property: {
      max: 65,
      min: 35,
      scale: 0,
      step: 1,
      type: 'value',
      unit: '℃',
    },
    type: 'obj',
    subType: 'value',
    defaultValue: '35',
  },
  {
    attr: 1152,
    canTrigger: true,
    code: 'temp_current',
    defaultRecommend: false,
    editPermission: true,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_c',
    id: 9,
    mode: 'ro',
    name: '出水温度',
    property: {
      max: 100,
      min: -30,
      scale: 0,
      step: 1,
      type: 'value',
      unit: '℃',
    },
    type: 'obj',
    subType: 'value',
    defaultValue: '-30',
  },
  {
    attr: 1152,
    canTrigger: true,
    code: 'inlet_temp',
    defaultRecommend: false,
    editPermission: true,
    executable: true,
    extContent: '',
    iconname: 'icon-wendu2',
    id: 11,
    mode: 'ro',
    name: '进水温度',
    property: {
      max: 100,
      min: -30,
      scale: 0,
      step: 1,
      type: 'value',
      unit: '℃',
    },
    type: 'obj',
    subType: 'value',
    defaultValue: '-30',
  },
  {
    attr: 1152,
    canTrigger: true,
    code: 'work_state',
    defaultRecommend: false,
    editPermission: true,
    executable: true,
    extContent: '',
    iconname: 'icon-zhuangtai',
    id: 15,
    mode: 'ro',
    name: '工作状态',
    property: {
      range: ['off', 'standby', 'bath_heating', 'zc_heating'],
      type: 'enum',
    },
    type: 'obj',
    subType: 'enum',
    defaultValue: 'off',
  },
  {
    attr: 1152,
    canTrigger: true,
    code: 'draught_fan_state',
    defaultRecommend: false,
    editPermission: true,
    executable: true,
    extContent: '',
    iconname: 'icon-zhuangtai',
    id: 17,
    mode: 'ro',
    name: '风机状态',
    property: {
      type: 'bool',
    },
    type: 'obj',
    subType: 'bool',
  },
  {
    attr: 1152,
    canTrigger: true,
    code: 'fault',
    defaultRecommend: false,
    editPermission: true,
    executable: true,
    extContent: '',
    iconname: 'icon-baojing',
    id: 23,
    mode: 'rw',
    name: '故障告警',
    property: {
      label: ['E0', 'E1', 'E2', 'E3', 'E4', 'E5', 'E6', 'E7', 'E8', 'EH', 'En', 'Eb', 'Ec'],
      maxlen: 13,
      type: 'bitmap',
    },
    type: 'obj',
    subType: 'bitmap',
    defaultValue: '0',
  },
  {
    attr: 1152,
    canTrigger: true,
    code: 'gas_consumption',
    defaultRecommend: false,
    editPermission: true,
    executable: true,
    extContent: '',
    iconname: 'icon-tongji2',
    id: 24,
    mode: 'ro',
    name: '耗气量',
    property: {
      max: 1000000000,
      min: 0,
      scale: 0,
      step: 1,
      type: 'value',
      unit: 'L',
    },
    type: 'obj',
    subType: 'value',
    defaultValue: '0',
  },
  {
    attr: 1152,
    canTrigger: true,
    code: 'water_total',
    defaultRecommend: false,
    editPermission: true,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_mode',
    id: 25,
    mode: 'ro',
    name: '耗水量',
    property: {
      max: 1000000000,
      min: 0,
      scale: 0,
      step: 1,
      type: 'value',
      unit: 'L',
    },
    type: 'obj',
    subType: 'value',
    defaultValue: '0',
  },
  {
    attr: 1152,
    canTrigger: true,
    code: 'turbo',
    defaultRecommend: false,
    editPermission: true,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_power2',
    id: 34,
    mode: 'rw',
    name: '增压（瀑布浴）',
    property: {
      type: 'bool',
    },
    type: 'obj',
    subType: 'bool',
    defaultValue: 'false',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'once_zero_cold',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: '',
    id: 101,
    mode: 'rw',
    name: '单次零冷水',
    property: {
      type: 'bool',
    },
    type: 'obj',
    subType: 'bool',
    defaultValue: 'false',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'zero_cold_jog_switch',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: '',
    id: 102,
    mode: 'rw',
    name: '零冷水水控预热开关',
    property: {
      type: 'bool',
    },
    type: 'obj',
    subType: 'bool',
    defaultValue: 'false',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'once_zero_cold_keep_time',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: '',
    id: 103,
    mode: 'rw',
    name: '单次零冷水保温时长',
    property: {
      max: 60,
      min: 10,
      scale: 0,
      step: 1,
      type: 'value',
      unit: '',
    },
    type: 'obj',
    subType: 'value',
    defaultValue: '10',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'zc_always_on',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: '',
    id: 104,
    mode: 'rw',
    name: '零冷水常开（24h零冷水，用于App云定时）',
    property: {
      type: 'bool',
    },
    type: 'obj',
    subType: 'bool',
    defaultValue: 'false',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'var_cap',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: '',
    id: 105,
    mode: 'rw',
    name: '变升',
    property: {
      range: ['20', '26'],
      type: 'enum',
    },
    type: 'obj',
    subType: 'enum',
    defaultValue: '20',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'bath_flow_set',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: '',
    id: 106,
    mode: 'rw',
    name: '浴缸流量设置',
    property: {
      max: 990,
      min: 50,
      scale: 0,
      step: 10,
      type: 'value',
      unit: '',
    },
    type: 'obj',
    subType: 'value',
    defaultValue: '50',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'zc_return_diff',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: '',
    id: 107,
    mode: 'rw',
    name: '零冷水回水温差',
    property: {
      max: 12,
      min: 3,
      scale: 0,
      step: 1,
      type: 'value',
      unit: '',
    },
    type: 'obj',
    subType: 'value',
    defaultValue: '3',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'bath_heat_done_alert',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: '',
    id: 108,
    mode: 'ro',
    name: '浴缸模式热水加热完成提醒',
    property: {
      type: 'bool',
    },
    type: 'obj',
    subType: 'bool',
    defaultValue: 'false',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'flame_state2',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: '',
    id: 120,
    mode: 'ro',
    name: '火焰状态',
    property: {
      type: 'bool',
    },
    type: 'obj',
    subType: 'bool',
    defaultValue: 'false',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'flow_state2',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: '',
    id: 121,
    mode: 'ro',
    name: '水流状态',
    property: {
      type: 'bool',
    },
    type: 'obj',
    subType: 'bool',
    defaultValue: 'false',
  },
] as const;
